name: Tests

on:
   workflow_dispatch:
   # push:
   pull_request:

jobs:
   test:
      runs-on: macos-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v6

         - name: Setup Node
           uses: actions/setup-node@v6
           with:
              node-version: 22

         - name: Setup pnpm
           uses: pnpm/action-setup@v5

         - name: Install frontend dependencies
           run: pnpm install

         - name: Setup Rust
           uses: dtolnay/rust-toolchain@stable

         - name: Rust cache
           uses: swatinem/rust-cache@v2
           with:
              workspaces: src-tauri

         - name: Run unit tests
           run: pnpm test:unit

         - name: Run E2E tests
           run: pnpm test:e2e
           env:
              E2E_FDA: 'false'
